include ../support/include.mk

all:
	(cd core;$(MAKE))
	(cd elog;$(MAKE))
	(cd erlrrd;$(MAKE))
	(cd errdb;$(MAKE))
	(cd misc;$(MAKE))
	(cd mochiweb;$(MAKE))


clean:
	(cd core;$(MAKE) clean)
	(cd elog;$(MAKE) clean)
	(cd erlrrd;$(MAKE) clean)
	(cd errdb;$(MAKE) clean)
	(cd misc;$(MAKE) clean)
	(cd mochiweb;$(MAKE) clean)

